export const workersActionTypes = {
  WORKERS_FETCH_START: "WORKERS_FETCH_START",
  WORKERS_FETCH_SUCCESS: "WORKERS_FETCH_SUCCESS",
  WORKERS_FETCH_FAILURE: "WORKERS_FETCH_FAILURE",
  ADD_WORKER_START: "ADD_WORKER_START",
  ADD_WORKER_SUCCESS: "ADD_WORKER_SUCCESS",
  ADD_WORKER_FAILURE: "ADD_WORKER_FAILURE",
  CLEAR_WORKERS: "CLEAR_WORKERS"
};
